package cn.zhny.ivs.webservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-13T17:24:57.561+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "CmsService", 
                  targetNamespace = "http://webservice.cms.hikvision.com") 
public class CmsService extends Service {


    public final static QName SERVICE = new QName("http://webservice.cms.hikvision.com", "CmsService");
    public final static QName CmsServiceHttpSoap11Endpoint = new QName("http://webservice.cms.hikvision.com", "CmsServiceHttpSoap11Endpoint");
    public final static QName CmsServiceHttpSoap12Endpoint = new QName("http://webservice.cms.hikvision.com", "CmsServiceHttpSoap12Endpoint");

    public CmsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    public CmsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CmsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CmsServicePortType
     */
    @WebEndpoint(name = "CmsServiceHttpSoap11Endpoint")
    public CmsServicePortType getCmsServiceHttpSoap11Endpoint() {
        return super.getPort(CmsServiceHttpSoap11Endpoint, CmsServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmsServicePortType
     */
    @WebEndpoint(name = "CmsServiceHttpSoap11Endpoint")
    public CmsServicePortType getCmsServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(CmsServiceHttpSoap11Endpoint, CmsServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns CmsServicePortType
     */
    @WebEndpoint(name = "CmsServiceHttpSoap12Endpoint")
    public CmsServicePortType getCmsServiceHttpSoap12Endpoint() {
        return super.getPort(CmsServiceHttpSoap12Endpoint, CmsServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmsServicePortType
     */
    @WebEndpoint(name = "CmsServiceHttpSoap12Endpoint")
    public CmsServicePortType getCmsServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(CmsServiceHttpSoap12Endpoint, CmsServicePortType.class, features);
    }

}
