package cn.zhny.ivs.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-13T17:24:57.487+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://webservice.cms.hikvision.com", name = "CmsServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CmsServicePortType {

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllCamera", output = "urn:getAllCameraResponse")
    @RequestWrapper(localName = "getAllCamera", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllCamera")
    @WebMethod(action = "urn:getAllCamera")
    @ResponseWrapper(localName = "getAllCameraResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllCameraResponse")
    public cn.zhny.ivs.webservice.CameraResult getAllCamera(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.cms.hikvision.com")
        cn.zhny.ivs.webservice.CommonPageReq args1
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllDevice", output = "urn:getAllDeviceResponse")
    @RequestWrapper(localName = "getAllDevice", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllDevice")
    @WebMethod(action = "urn:getAllDevice")
    @ResponseWrapper(localName = "getAllDeviceResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllDeviceResponse")
    public cn.zhny.ivs.webservice.DeviceResult getAllDevice(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.cms.hikvision.com")
        cn.zhny.ivs.webservice.CommonPageReq args1
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:userLogout", output = "urn:userLogoutResponse")
    @RequestWrapper(localName = "userLogout", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.UserLogout")
    @WebMethod(action = "urn:userLogout")
    @ResponseWrapper(localName = "userLogoutResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.UserLogoutResponse")
    public cn.zhny.ivs.webservice.LogoutResult userLogout(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:setCmsTime", output = "urn:setCmsTimeResponse")
    @RequestWrapper(localName = "setCmsTime", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.SetCmsTime")
    @WebMethod(action = "urn:setCmsTime")
    @ResponseWrapper(localName = "setCmsTimeResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.SetCmsTimeResponse")
    public cn.zhny.ivs.webservice.CmsTimingResult setCmsTime(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args1
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllControlCenterForList", output = "urn:getAllControlCenterForListResponse")
    @RequestWrapper(localName = "getAllControlCenterForList", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllControlCenterForList")
    @WebMethod(action = "urn:getAllControlCenterForList")
    @ResponseWrapper(localName = "getAllControlCenterForListResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllControlCenterForListResponse")
    public cn.zhny.ivs.webservice.ControlUnitsResult getAllControlCenterForList(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllCameraInfoForList", output = "urn:getAllCameraInfoForListResponse")
    @RequestWrapper(localName = "getAllCameraInfoForList", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllCameraInfoForList")
    @WebMethod(action = "urn:getAllCameraInfoForList")
    @ResponseWrapper(localName = "getAllCameraInfoForListResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllCameraInfoForListResponse")
    public cn.zhny.ivs.webservice.CameraInfoResult getAllCameraInfoForList(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllServers", output = "urn:getAllServersResponse")
    @RequestWrapper(localName = "getAllServers", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllServers")
    @WebMethod(action = "urn:getAllServers")
    @ResponseWrapper(localName = "getAllServersResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllServersResponse")
    public cn.zhny.ivs.webservice.ServerResult getAllServers(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getCameraInRecordLocation", output = "urn:getCameraInRecordLocationResponse")
    @RequestWrapper(localName = "getCameraInRecordLocation", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetCameraInRecordLocation")
    @WebMethod(action = "urn:getCameraInRecordLocation")
    @ResponseWrapper(localName = "getCameraInRecordLocationResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetCameraInRecordLocationResponse")
    public cn.zhny.ivs.webservice.CameraReLocationResult getCameraInRecordLocation(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getCameraInfoByDeviceInfo", output = "urn:getCameraInfoByDeviceInfoResponse")
    @RequestWrapper(localName = "getCameraInfoByDeviceInfo", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetCameraInfoByDeviceInfo")
    @WebMethod(action = "urn:getCameraInfoByDeviceInfo")
    @ResponseWrapper(localName = "getCameraInfoByDeviceInfoResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetCameraInfoByDeviceInfoResponse")
    public cn.zhny.ivs.webservice.CameraResult getCameraInfoByDeviceInfo(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args1
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getPlaybackParam", output = "urn:getPlaybackParamResponse")
    @RequestWrapper(localName = "getPlaybackParam", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetPlaybackParam")
    @WebMethod(action = "urn:getPlaybackParam")
    @ResponseWrapper(localName = "getPlaybackParamResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetPlaybackParamResponse")
    public cn.zhny.ivs.webservice.PlaybackResult getPlaybackParam(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.cms.hikvision.com")
        cn.zhny.ivs.webservice.PlaybackParamReq args1
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllStreamServer", output = "urn:getAllStreamServerResponse")
    @RequestWrapper(localName = "getAllStreamServer", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllStreamServer")
    @WebMethod(action = "urn:getAllStreamServer")
    @ResponseWrapper(localName = "getAllStreamServerResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllStreamServerResponse")
    public cn.zhny.ivs.webservice.StreamServerResult getAllStreamServer(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:userOnlineHeartbeat", output = "urn:userOnlineHeartbeatResponse")
    @RequestWrapper(localName = "userOnlineHeartbeat", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.UserOnlineHeartbeat")
    @WebMethod(action = "urn:userOnlineHeartbeat")
    @ResponseWrapper(localName = "userOnlineHeartbeatResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.UserOnlineHeartbeatResponse")
    public cn.zhny.ivs.webservice.CommonResult userOnlineHeartbeat(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getPreviewParam", output = "urn:getPreviewParamResponse")
    @RequestWrapper(localName = "getPreviewParam", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetPreviewParam")
    @WebMethod(action = "urn:getPreviewParam")
    @ResponseWrapper(localName = "getPreviewParamResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetPreviewParamResponse")
    public cn.zhny.ivs.webservice.PreviewResult getPreviewParam(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args1
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllRegionInfoForList", output = "urn:getAllRegionInfoForListResponse")
    @RequestWrapper(localName = "getAllRegionInfoForList", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllRegionInfoForList")
    @WebMethod(action = "urn:getAllRegionInfoForList")
    @ResponseWrapper(localName = "getAllRegionInfoForListResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllRegionInfoForListResponse")
    public cn.zhny.ivs.webservice.RegionInfoResult getAllRegionInfoForList(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getAllVrmServer", output = "urn:getAllVrmServerResponse")
    @RequestWrapper(localName = "getAllVrmServer", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllVrmServer")
    @WebMethod(action = "urn:getAllVrmServer")
    @ResponseWrapper(localName = "getAllVrmServerResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetAllVrmServerResponse")
    public cn.zhny.ivs.webservice.VrmServerResult getAllVrmServer(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:userLogin", output = "urn:userLoginResponse")
    @RequestWrapper(localName = "userLogin", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.UserLogin")
    @WebMethod(action = "urn:userLogin")
    @ResponseWrapper(localName = "userLoginResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.UserLoginResponse")
    public cn.zhny.ivs.webservice.LoginResult userLogin(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.Integer args3,
        @WebParam(name = "args4", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args4
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.cms.hikvision.com")
    @Action(input = "urn:getVrmRecordScheduleListForCMS", output = "urn:getVrmRecordScheduleListForCMSResponse")
    @RequestWrapper(localName = "getVrmRecordScheduleListForCMS", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetVrmRecordScheduleListForCMS")
    @WebMethod(action = "urn:getVrmRecordScheduleListForCMS")
    @ResponseWrapper(localName = "getVrmRecordScheduleListForCMSResponse", targetNamespace = "http://webservice.cms.hikvision.com", className = "cn.zhny.ivs.webservice.GetVrmRecordScheduleListForCMSResponse")
    public cn.zhny.ivs.webservice.VrmRecordScheduleListForPMS getVrmRecordScheduleListForCMS(
        @WebParam(name = "args0", targetNamespace = "http://webservice.cms.hikvision.com")
        java.lang.String args0
    );
}
